id: AC008BC35
title: The Aspiration of the Vajradhātu Maṇḍala
type: translation
pechas:
- I72AB3837
- I37B7064B
- I737CA948
- I34504A82
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:16.026039
  last_modified_at: 2023-01-04 12:00:16.026049
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I72AB3837/EFCF: '0737'
  I37B7064B/BAC3: '0737'
  I737CA948/8AAF: '0737'
  I34504A82/3C90: '0737'
